(function () {
  const configPanel=document.querySelector('[data-config-panel]'),loginPanel=document.querySelector('[data-login-panel]'),dashboard=document.querySelector('[data-dashboard]'),workspace=document.querySelector('[data-cms-workspace]'),tabs=document.querySelector('[data-tabs]');
  let content=null,currentTab='global',demo=false;
  const field=(name,label,type='text',required=false)=>({name,label,type,required});
  const sections={
    global:{label:'기본 · SNS',type:'single',key:'global',fields:[field('studioName','스튜디오 이름','text',true),field('email','이메일','email'),field('navAbout','About 메뉴명'),field('navGames','Games 메뉴명'),field('navGoods','Goods 메뉴명'),field('navNews','News 메뉴명'),field('youtube','YouTube URL','url'),field('instagram','Instagram URL','url'),field('discord','Discord URL','url'),field('twitter','X / Twitter URL','url'),field('footerTitle','푸터 첫 줄'),field('footerAccent','푸터 강조 문구'),field('footerNote','푸터 하단 문구')]},
    home:{label:'홈',type:'single',key:'home',fields:[field('heroKicker','히어로 작은 문구'),field('heroTitle','히어로 제목 · 줄바꿈 가능','textarea'),field('heroCopy','히어로 설명','textarea'),field('ticker','움직이는 티커 문구','textarea'),field('introTitle','소개 제목 · 줄바꿈 가능','textarea'),field('introCopy','소개 본문','textarea'),field('featuredGameId','대표 게임 URL ID')]},
    about:{label:'About',type:'single',key:'about',fields:[field('pageTitle','페이지 제목 · 줄바꿈 가능','textarea'),field('deck','상단 설명','textarea'),field('introTitle','메인 소개 제목','textarea'),field('manifestoLines','선언문 · 한 줄에 LABEL | 문장','textarea')]},
    team:{label:'개발자',type:'collection',key:'team',fields:[field('id','URL ID','text',true),field('name','한글 이름','text',true),field('englishName','영문 이름'),field('role','직무'),field('bio','카드 소개','textarea'),field('description','상세 소개','textarea'),field('initial','큰 이니셜'),field('image','이미지 URL 또는 assets 경로'),field('order','정렬 순서','number')]},
    games:{label:'게임',type:'collection',key:'games',pageKey:'gamesPage',pageFields:[field('pageTitle','페이지 제목','textarea'),field('deck','페이지 설명','textarea')],fields:[field('id','URL ID','text',true),field('title','게임 이름','text',true),field('status','개발 상태'),field('genre','장르'),field('platform','플랫폼'),field('release','출시 정보'),field('summary','목록 요약','textarea'),field('description','상세 설명','textarea'),field('image','대표 이미지 URL 또는 assets 경로'),field('accent','포인트 색상','color'),field('order','정렬 순서','number')]},
    goods:{label:'굿즈',type:'collection',key:'goods',pageKey:'goodsPage',pageFields:[field('pageTitle','페이지 제목','textarea'),field('deck','페이지 설명','textarea'),field('collectionTitle','컬렉션 제목','textarea')],fields:[field('id','URL ID','text',true),field('title','상품명','text',true),field('spec','제품 사양'),field('price','가격'),field('visualText','비주얼 문자'),field('description','상세 설명','textarea'),field('image','대표 이미지 URL 또는 assets 경로'),field('buyUrl','구매 링크 URL','url'),field('order','정렬 순서','number')]},
    news:{label:'뉴스',type:'collection',key:'news',pageKey:'newsPage',pageFields:[field('pageTitle','페이지 제목','textarea'),field('deck','페이지 설명','textarea')],fields:[field('id','URL ID','text',true),field('date','날짜','date'),field('category','카테고리'),field('title','제목','text',true),field('excerpt','목록 요약','textarea'),field('body','기사 본문','textarea'),field('image','대표 이미지 URL 또는 assets 경로'),field('order','정렬 순서','number')]}
  };

  const show=(panel)=>[configPanel,loginPanel,dashboard].forEach(el=>el.hidden=el!==panel);
  async function openDashboard(){content=structuredClone(await ContentStore.load(true));show(dashboard);document.querySelector('[data-admin-mode]').textContent=demo?'로컬 데모 모드 · 이 브라우저에만 저장':'Supabase 연결됨 · 게시하면 즉시 반영';renderTabs();renderSection();}
  async function init(){if(!ContentStore.configured){show(configPanel);return;}if(ContentStore.session())await openDashboard();else show(loginPanel);}
  document.querySelector('[data-demo]')?.addEventListener('click',async()=>{demo=true;await openDashboard();});
  document.querySelector('[data-login-form]')?.addEventListener('submit',async e=>{e.preventDefault();const data=new FormData(e.currentTarget),message=document.querySelector('[data-login-message]');try{await ContentStore.login(data.get('email'),data.get('password'));message.textContent='';await openDashboard();}catch(error){message.textContent=error.message;}});
  document.querySelector('[data-logout]')?.addEventListener('click',()=>{ContentStore.logout();location.reload();});
  document.querySelector('[data-publish]')?.addEventListener('click',async e=>{const button=e.currentTarget;button.disabled=true;button.textContent='저장 중…';try{const result=await ContentStore.save(content);button.textContent=result.preview?'데모 저장 완료':'게시 완료';setTimeout(()=>button.textContent='변경사항 게시',1800);}catch(error){alert(error.message);button.textContent='변경사항 게시';}finally{button.disabled=false;}});

  function renderTabs(){tabs.replaceChildren();Object.entries(sections).forEach(([key,section])=>{const button=document.createElement('button');button.type='button';button.textContent=section.label;button.classList.toggle('active',key===currentTab);button.addEventListener('click',()=>{currentTab=key;renderTabs();renderSection();});tabs.appendChild(button);});}
  function inputFor(def,value=''){const label=document.createElement('label');label.textContent=def.label;let input;if(def.type==='textarea'){input=document.createElement('textarea');input.rows=def.name==='body'||def.name==='description'?8:4;}else{input=document.createElement('input');input.type=def.type;}input.name=def.name;input.value=value??'';input.required=def.required;label.appendChild(input);return label;}
  function values(form,defs){const data=new FormData(form),result={};defs.forEach(def=>{let value=data.get(def.name)??'';if(def.type==='number')value=Number(value)||0;result[def.name]=typeof value==='string'?value.trim():value;});return result;}
  function singleForm(key,defs){const form=document.createElement('form');form.className='admin-form cms-single-form';let source={...(content[key]||{})};if(key==='about')source.manifestoLines=(source.manifesto||[]).map(item=>`${item.label} | ${item.text}`).join('\n');defs.forEach(def=>form.appendChild(inputFor(def,source[def.name])));const button=document.createElement('button');button.className='admin-primary';button.type='submit';button.textContent='이 섹션 저장';form.appendChild(button);form.addEventListener('submit',e=>{e.preventDefault();const next=values(form,defs);if(key==='about'){next.manifesto=next.manifestoLines.split('\n').filter(Boolean).map(line=>{const [label,...rest]=line.split('|');return{label:label.trim(),text:rest.join('|').trim()};});delete next.manifestoLines;}content[key]={...(content[key]||{}),...next};flash(button);});return form;}
  function flash(button){const old=button.textContent;button.textContent='편집본에 저장됨';setTimeout(()=>button.textContent=old,1200);}
  function renderSection(){workspace.replaceChildren();const section=sections[currentTab];const title=document.createElement('div');title.className='admin-section-title';const h2=document.createElement('h2');h2.textContent=section.label;title.appendChild(h2);workspace.appendChild(title);if(section.type==='single'){workspace.appendChild(singleForm(section.key,section.fields));return;}renderCollection(section);}
  function renderCollection(section){if(section.pageKey){const details=document.createElement('details');details.className='cms-page-settings';const summary=document.createElement('summary');summary.textContent='페이지 제목과 설명 수정';details.append(summary,singleForm(section.pageKey,section.pageFields));workspace.appendChild(details);}const layout=document.createElement('div');layout.className='admin-layout cms-collection-layout';const listWrap=document.createElement('aside');listWrap.className='admin-game-list';const listTitle=document.createElement('div');listTitle.className='admin-section-title';const label=document.createElement('h2');label.textContent=`${section.label} 목록`;const add=document.createElement('button');add.type='button';add.textContent='새 항목';listTitle.append(label,add);const list=document.createElement('div');listWrap.append(listTitle,list);const editor=document.createElement('section');editor.className='admin-editor';layout.append(listWrap,editor);workspace.appendChild(layout);let selected=null;
    const drawList=()=>{list.replaceChildren();(content[section.key]||[]).sort((a,b)=>(a.order||0)-(b.order||0)).forEach(item=>{const row=document.createElement('button');row.type='button';row.className='cms-list-item';const strong=document.createElement('strong');strong.textContent=item.title||item.name;const small=document.createElement('span');small.textContent=item.id;row.append(strong,small);row.addEventListener('click',()=>{selected=item.id;drawEditor(item);});list.appendChild(row);});};
    const drawEditor=(item={})=>{editor.replaceChildren();const heading=document.createElement('div');heading.className='admin-section-title';const name=document.createElement('h2');name.textContent=item.id?'항목 수정':'새 항목 추가';heading.appendChild(name);if(item.id){const remove=document.createElement('button');remove.type='button';remove.textContent='삭제';remove.addEventListener('click',()=>{if(!confirm(`“${item.title||item.name}” 항목을 삭제할까요?`))return;content[section.key]=content[section.key].filter(entry=>entry.id!==item.id);selected=null;drawList();drawEditor({});});heading.appendChild(remove);}const form=document.createElement('form');form.className='admin-form';section.fields.forEach(def=>form.appendChild(inputFor(def,item[def.name]??(def.name==='order'?(content[section.key]?.length||0)+1:def.name==='image'?'assets/hero-palace.png':def.name==='accent'?'#c7ff2f':''))));const save=document.createElement('button');save.type='submit';save.className='admin-primary';save.textContent='항목 저장';form.appendChild(save);form.addEventListener('submit',e=>{e.preventDefault();const next=values(form,section.fields);next.id=ContentStore.makeId(next.id||next.title||next.name);const duplicate=(content[section.key]||[]).some(entry=>entry.id===next.id&&entry.id!==selected);if(duplicate)return alert('이미 사용 중인 URL ID입니다.');if(selected)content[section.key]=content[section.key].map(entry=>entry.id===selected?next:entry);else content[section.key]=[...(content[section.key]||[]),next];selected=next.id;drawList();drawEditor(next);});editor.append(heading,form);};
    add.addEventListener('click',()=>{selected=null;drawEditor({});});drawList();drawEditor({});
  }
  init();
})();
