(function () {
  const configPanel=document.querySelector('[data-config-panel]'),loginPanel=document.querySelector('[data-login-panel]'),dashboard=document.querySelector('[data-dashboard]'),workspace=document.querySelector('[data-cms-workspace]'),tabs=document.querySelector('[data-tabs]');
  let content=null,currentTab='global',demo=false;
  const field=(name,label,type='text',required=false,extra={})=>({name,label,type,required,...extra});
  const sections={
    global:{label:'기본 · SNS',type:'single',key:'global',fields:[field('studioName','스튜디오 이름','text',true),field('email','이메일','email'),field('navAbout','About 메뉴명'),field('navGames','Games 메뉴명'),field('navRoadmap','Roadmap 메뉴명'),field('navGoods','Goods 메뉴명'),field('navNews','News 메뉴명'),field('youtube','YouTube URL','url'),field('instagram','Instagram URL','url'),field('discord','Discord URL','url'),field('twitter','X / Twitter URL','url'),field('footerTitle','푸터 첫 줄'),field('footerAccent','푸터 강조 문구'),field('footerNote','푸터 하단 문구')]},
    home:{label:'홈',type:'single',key:'home',fields:[field('heroKicker','히어로 작은 문구'),field('heroTitle','히어로 제목 · 줄바꿈 가능','textarea'),field('heroCopy','히어로 설명','textarea'),field('ticker','움직이는 티커 문구','textarea'),field('introTitle','소개 제목 · 줄바꿈 가능','textarea'),field('introCopy','소개 본문','textarea'),field('featuredGameId','대표 게임 URL ID')]},
    about:{label:'About',type:'single',key:'about',fields:[field('pageTitle','페이지 제목 · 줄바꿈 가능','textarea'),field('deck','상단 설명','textarea'),field('introTitle','메인 소개 제목','textarea'),field('manifestoLines','선언문 · 한 줄에 LABEL | 문장','textarea')]},
    team:{label:'개발자',type:'collection',key:'team',fields:[field('id','URL ID','text',true),field('name','한글 이름','text',true),field('englishName','영문 이름'),field('role','직무'),field('bio','카드 소개','textarea'),field('description','상세 소개','textarea'),field('initial','큰 이니셜'),field('image','이미지 URL 또는 assets 경로'),field('order','정렬 순서','number')]},
    games:{label:'게임',type:'collection',key:'games',pageKey:'gamesPage',pageFields:[field('pageTitle','페이지 제목','textarea'),field('deck','페이지 설명','textarea')],fields:[field('id','URL ID','text',true),field('title','게임 이름','text',true),field('status','개발 상태'),field('genre','장르'),field('platform','플랫폼'),field('release','출시 정보'),field('summary','목록 요약','textarea'),field('description','상세 설명','textarea'),field('image','대표 이미지 URL 또는 assets 경로'),field('accent','포인트 색상','color'),field('order','정렬 순서','number')]},
    roadmap:{label:'로드맵',type:'collection',key:'roadmap',pageKey:'roadmapPage',pageFields:[field('pageTitle','페이지 제목 · 줄바꿈 가능','textarea'),field('deck','상단 설명','textarea'),field('introTitle','로드맵 섹션 제목 · 줄바꿈 가능','textarea'),field('rotatingWords','강조 전환 단어 · 쉼표로 구분'),field('focusLabel','현재 집중 영역 라벨'),field('focusTitle','현재 집중 영역 제목 · 줄바꿈 가능','textarea'),field('focusDescription','현재 집중 영역 설명','textarea'),field('focusProgress','현재 진행률 0-100','number'),field('focusGameId','현재 집중 영역과 연결할 게임 ID'),field('metricTeam','왼쪽 패널 TEAM 값 · 비우면 자동'),field('metricWorlds','왼쪽 패널 WORLDS 값 · 비우면 자동'),field('metricNext','왼쪽 패널 NEXT DROP 값')],fields:[field('id','URL ID','text',true),field('period','기간 / 날짜'),field('state','상태 스타일','select',false,{options:[['done','완료'],['active','진행중'],['next','다음'],['planned','예정']]}),field('status','상태 표시 문구'),field('title','로드맵 제목','text',true),field('description','설명','textarea'),field('gameId','연결할 게임 ID · games의 URL ID와 같게'),field('order','정렬 순서','number')]},
    goods:{label:'굿즈',type:'collection',key:'goods',pageKey:'goodsPage',pageFields:[field('pageTitle','페이지 제목','textarea'),field('deck','페이지 설명','textarea'),field('collectionTitle','컬렉션 제목','textarea')],fields:[field('id','URL ID','text',true),field('title','상품명','text',true),field('spec','제품 사양'),field('price','가격'),field('visualText','비주얼 문자'),field('description','상세 설명','textarea'),field('image','대표 이미지 URL 또는 assets 경로'),field('buyUrl','구매 링크 URL','url'),field('order','정렬 순서','number')]},
    news:{label:'뉴스',type:'collection',key:'news',pageKey:'newsPage',pageFields:[field('pageTitle','페이지 제목','textarea'),field('deck','페이지 설명','textarea')],fields:[field('id','URL ID','text',true),field('date','날짜','date'),field('category','카테고리'),field('title','제목','text',true),field('excerpt','목록 요약','textarea'),field('body','기사 본문','textarea'),field('image','대표 이미지 URL 또는 assets 경로'),field('order','정렬 순서','number')]}
  };
  const defaultRoadmapPage={pageTitle:'NEXT\nPATCHES.',deck:'Cinderella가 지금 만들고 있고, 곧 공개하고 싶은 것들. 일정은 개발 상황에 따라 바뀔 수 있지만 방향은 여기에서 확인할 수 있습니다.',introTitle:'작은 팀의 다음\n발자국.',rotatingWords:'발자국,빌드,장면,약속',focusLabel:'Current focus',focusTitle:'Glass Midnight\nVertical Slice',focusDescription:'대표 게임의 핵심 루프, 분위기, 첫 플레이 감각을 하나의 빌드로 묶는 중입니다.',focusProgress:42,focusGameId:'glass-midnight',metricTeam:'',metricWorlds:'',metricNext:'Playtest build'};
  const defaultRoadmap=[{id:'site-identity',period:'2026.06',state:'done',status:'DONE',title:'사이트와 스튜디오 아이덴티티 정리',description:'클린 URL, 파비콘, 인터랙션, 팀/게임 소개 구조를 정리해서 공개 가능한 형태로 다듬습니다.',gameId:'',order:1},{id:'glass-midnight-slice',period:'2026 Q3',state:'active',status:'IN PROGRESS',title:'Glass Midnight 핵심 빌드 제작',description:'전투/탐험/서사 흐름이 한 번에 느껴지는 버티컬 슬라이스를 만들고 내부 테스트를 반복합니다.',gameId:'glass-midnight',order:2},{id:'first-playtest',period:'2026 Q4',state:'next',status:'NEXT',title:'첫 외부 플레이테스트',description:'소규모 플레이어에게 테스트 빌드를 공유하고, 조작감·난이도·분위기 피드백을 모읍니다.',gameId:'glass-midnight',order:3},{id:'store-demo',period:'2027 Q1',state:'planned',status:'PLANNED',title:'스토어 페이지와 데모 준비',description:'스크린샷, 트레일러, 소개 문구를 정리하고 플레이 가능한 공개 데모 범위를 확정합니다.',gameId:'second-sun',order:4},{id:'launch-build',period:'2027+',state:'planned',status:'TBA',title:'출시 빌드로 확장',description:'콘텐츠 볼륨, 사운드, 최적화, 현지화, QA를 거쳐 정식 출시를 향해 확장합니다.',gameId:'',order:5}];

  const show=(panel)=>[configPanel,loginPanel,dashboard].forEach(el=>el.hidden=el!==panel);
  function ensureRoadmapDefaults(){content.roadmapPage={...defaultRoadmapPage,...(content.roadmapPage||{})};if(!Array.isArray(content.roadmap)||!content.roadmap.length)content.roadmap=structuredClone(defaultRoadmap);}
  async function openDashboard(){content=structuredClone(await ContentStore.load(true));ensureRoadmapDefaults();syncGameDatalist();show(dashboard);document.querySelector('[data-admin-mode]').textContent=demo?'로컬 데모 모드 · 이 브라우저에만 저장':'Supabase 연결됨 · 게시하면 즉시 반영';renderTabs();renderSection();}
  async function init(){if(!ContentStore.configured){show(configPanel);return;}if(ContentStore.session())await openDashboard();else show(loginPanel);}
  document.querySelector('[data-demo]')?.addEventListener('click',async()=>{demo=true;await openDashboard();});
  document.querySelector('[data-login-form]')?.addEventListener('submit',async e=>{e.preventDefault();const data=new FormData(e.currentTarget),message=document.querySelector('[data-login-message]');try{await ContentStore.login(data.get('email'),data.get('password'));message.textContent='';await openDashboard();}catch(error){message.textContent=error.message;}});
  document.querySelector('[data-logout]')?.addEventListener('click',()=>{ContentStore.logout();location.reload();});
  document.querySelector('[data-publish]')?.addEventListener('click',async e=>{const button=e.currentTarget;button.disabled=true;button.textContent='저장 중…';try{const result=await ContentStore.save(content);button.textContent=result.preview?'데모 저장 완료':'게시 완료';setTimeout(()=>button.textContent='변경사항 게시',1800);}catch(error){alert(error.message);button.textContent='변경사항 게시';}finally{button.disabled=false;}});

  function renderTabs(){tabs.replaceChildren();Object.entries(sections).forEach(([key,section])=>{const button=document.createElement('button');button.type='button';button.textContent=section.label;button.classList.toggle('active',key===currentTab);button.addEventListener('click',()=>{currentTab=key;renderTabs();renderSection();});tabs.appendChild(button);});}
  function syncGameDatalist(){let datalist=document.getElementById('admin-game-id-options');if(!datalist){datalist=document.createElement('datalist');datalist.id='admin-game-id-options';document.body.appendChild(datalist);}datalist.replaceChildren(...(content?.games||[]).map(game=>{const option=document.createElement('option');option.value=game.id;option.label=game.title||game.id;return option;}));}
  function inputFor(def,value=''){const label=document.createElement('label');label.textContent=def.label;let input;if(def.type==='textarea'){input=document.createElement('textarea');input.rows=def.name==='body'||def.name==='description'?8:4;}else if(def.type==='select'){input=document.createElement('select');(def.options||[]).forEach(([optionValue,optionLabel])=>{const option=document.createElement('option');option.value=optionValue;option.textContent=optionLabel;input.appendChild(option);});}else{input=document.createElement('input');input.type=def.type;}if(def.name==='gameId'||def.name==='focusGameId')input.setAttribute('list','admin-game-id-options');input.name=def.name;input.value=value??'';input.required=def.required;label.appendChild(input);return label;}
  function values(form,defs){const data=new FormData(form),result={};defs.forEach(def=>{let value=data.get(def.name)??'';if(def.type==='number')value=String(value).trim()===''?null:Number(value)||0;result[def.name]=typeof value==='string'?value.trim():value;});return result;}
  function singleForm(key,defs){const form=document.createElement('form');form.className='admin-form cms-single-form';let source={...(content[key]||{})};if(key==='about')source.manifestoLines=(source.manifesto||[]).map(item=>`${item.label} | ${item.text}`).join('\n');defs.forEach(def=>form.appendChild(inputFor(def,source[def.name])));const button=document.createElement('button');button.className='admin-primary';button.type='submit';button.textContent='이 섹션 저장';form.appendChild(button);form.addEventListener('submit',e=>{e.preventDefault();const next=values(form,defs);if(key==='about'){next.manifesto=next.manifestoLines.split('\n').filter(Boolean).map(line=>{const [label,...rest]=line.split('|');return{label:label.trim(),text:rest.join('|').trim()};});delete next.manifestoLines;}content[key]={...(content[key]||{}),...next};flash(button);});return form;}
  function flash(button){const old=button.textContent;button.textContent='편집본에 저장됨';setTimeout(()=>button.textContent=old,1200);}
  function renderSection(){workspace.replaceChildren();const section=sections[currentTab];const title=document.createElement('div');title.className='admin-section-title';const h2=document.createElement('h2');h2.textContent=section.label;title.appendChild(h2);workspace.appendChild(title);if(section.type==='single'){workspace.appendChild(singleForm(section.key,section.fields));return;}renderCollection(section);}
  function renderCollection(section){if(section.pageKey){const details=document.createElement('details');details.className='cms-page-settings';const summary=document.createElement('summary');summary.textContent='페이지 제목과 설명 수정';details.append(summary,singleForm(section.pageKey,section.pageFields));workspace.appendChild(details);}const layout=document.createElement('div');layout.className='admin-layout cms-collection-layout';const listWrap=document.createElement('aside');listWrap.className='admin-game-list';const listTitle=document.createElement('div');listTitle.className='admin-section-title';const label=document.createElement('h2');label.textContent=`${section.label} 목록`;const add=document.createElement('button');add.type='button';add.textContent='새 항목';listTitle.append(label,add);const list=document.createElement('div');listWrap.append(listTitle,list);const editor=document.createElement('section');editor.className='admin-editor';layout.append(listWrap,editor);workspace.appendChild(layout);let selected=null;
    const drawList=()=>{list.replaceChildren();(content[section.key]||[]).sort((a,b)=>(a.order||0)-(b.order||0)).forEach(item=>{const row=document.createElement('button');row.type='button';row.className='cms-list-item';const strong=document.createElement('strong');strong.textContent=item.title||item.name;const small=document.createElement('span');small.textContent=item.id;row.append(strong,small);row.addEventListener('click',()=>{selected=item.id;drawEditor(item);});list.appendChild(row);});};
    const drawEditor=(item={})=>{editor.replaceChildren();const heading=document.createElement('div');heading.className='admin-section-title';const name=document.createElement('h2');name.textContent=item.id?'항목 수정':'새 항목 추가';heading.appendChild(name);if(item.id){const remove=document.createElement('button');remove.type='button';remove.textContent='삭제';remove.addEventListener('click',()=>{if(!confirm(`“${item.title||item.name}” 항목을 삭제할까요?`))return;content[section.key]=content[section.key].filter(entry=>entry.id!==item.id);selected=null;drawList();drawEditor({});});heading.appendChild(remove);}const form=document.createElement('form');form.className='admin-form';section.fields.forEach(def=>form.appendChild(inputFor(def,item[def.name]??(def.defaultValue??(def.name==='order'?(content[section.key]?.length||0)+1:def.name==='image'?'assets/hero-palace.png':def.name==='accent'?'#c7ff2f':def.name==='state'?'planned':'')))));if(section.key==='roadmap'){const hint=document.createElement('p');hint.className='admin-field-hint';hint.textContent=`연결 가능한 게임 ID: ${(content.games||[]).map(game=>game.id).join(', ')||'아직 등록된 게임 없음'}`;form.appendChild(hint);}const save=document.createElement('button');save.type='submit';save.className='admin-primary';save.textContent='항목 저장';form.appendChild(save);form.addEventListener('submit',e=>{e.preventDefault();const next=values(form,section.fields);next.id=ContentStore.makeId(next.id||next.title||next.name);const duplicate=(content[section.key]||[]).some(entry=>entry.id===next.id&&entry.id!==selected);if(duplicate)return alert('이미 사용 중인 URL ID입니다.');if(selected)content[section.key]=content[section.key].map(entry=>entry.id===selected?next:entry);else content[section.key]=[...(content[section.key]||[]),next];selected=next.id;if(section.key==='games')syncGameDatalist();drawList();drawEditor(next);});editor.append(heading,form);};
    add.addEventListener('click',()=>{selected=null;drawEditor({});});drawList();drawEditor({});
  }
  init();
})();
